### ISSUE TITLE
SCTransform and Jackstraw

### ISSUE THREAD

**Issue by Rebecza** [tilschaef/scRNA-seq#10]
While testing the workflow, JackStraw appeared not to work together with SCTransform.

So when switching on both variables, the workflow crashes. 

We should only JackStraw allow to run when `run.sct` is `FALSE` (can one add multiple conditions to the `{r running JackStraw, eval=params$run.jackstraw}`, `eval` argument?). (and state when it didn't run because of this setting's value)

**Comment by Rebecza** [comment]
For now I tried updating the `params$run.jackstraw`, with the inverse of the `params$run.sct`

**Comment by tilschaef** [comment]
I re-added them to the eval parameter, basically `eval=!params$run.sct && params$run.jackstraw`
