### ISSUE TITLE
Output of params settings

### ISSUE THREAD

**Issue by Rebecza** [tilschaef/scRNA-seq#12]
**Question:** Would it be possible to generate an overview with all the Parameter settings used for the knit?

This is especially useful when running this script separate of the s2s workflow, because there is no documentation of the used settings in a config file there. 

At the moment, this information is not visible in the knit. (Maybe we could print it somewhere at the bottom of the file?)

**Comment by tilschaef** [comment]
There should be a way to save the params object to a yam, txt file. Will have a look

**Comment by tilschaef** [comment]
Added function to write settings to .yaml file in the output directory.
