### ISSUE TITLE
Filepath issues

### ISSUE THREAD

**Issue by Rebecza** [tilschaef/scRNA-seq#13]
_Not sure if this is a problem when running directly on s2s output:_

I run the .rmd file separately from s2s, with: knit with parameters, in RStudio. 

Thereby I run the .rmd from the location where it is saved: the `analysis/` folder, where also all the subsequent scripts and child-rmds are stored. Within the `kb_seurat_pp.rmd` however, you are searching for these extra scripts and files in `analysis/`.

So for me, with the settings as they were and using the `kb_seurat_pp.rmd`, from the location where it is stored, it did not work. But I don't know if you normally in a run, locate the somewhere else?

**Comment by Rebecza** [comment]
I now removed for instance in the following similar lines of code: 
`res <- knitr::knit_child(here::here("analysis", norm.rmd), quiet = TRUE, envir=environment())`

Like this: 
`res <- knitr::knit_child(here::here(norm.rmd), quiet = TRUE, envir=environment())`

This solved it for me, but not sure if this will clash with any settings while running it from s2s workflow directly?

**Comment by tilschaef** [comment]
Okay, since we now have the rmd and all dependencies in the same folder, there is really no need for` here` anymore. I removed it for now and there should not be any clashes with file references anymore.
