### ISSUE TITLE
Parameter extract_meta_columns

### ISSUE THREAD

**Issue by Rebecza** [tilschaef/scRNA-seq#9]
I use the `extract_meta_columns` to generate a meta data table from my cell names. 

For this variable, I always add `well` as the last field: since in the loading of the matrix, the well-id is added (with '_') to the cell names. Is there a way to make this standard? Because, one would not expecting that to be the last field when filling in the parameters (or config file), since the folder names do not include this field as well.

_Maybe the cell name extraction in general, is too specific a method to my and only some other researcher's convention of writing the plates/columns, and therefore this is not worth looking into._ 

However, I was thinking:
* Maybe we could always try to extract at least a `Library` variable and a `Well` name to add to the metadata? (Thereby always adding `,Well` at the end of the `extract_meta_columns` variable). 
* Alternative: the last field is removed before generating the meta data table from column names.

**Comment by tilschaef** [comment]
I see, yes we can make it standard that well and library are  always appended to vector of meta_columns.  

However, i think that is indeed a very specific application and we have now 3 different ways to add meta data information :).

**Comment by tilschaef** [comment]
a well/barcode column is now automatically added to the meta data and the user does not have to specify it explicitly.
